name: Date Picker Tests

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  local-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Start dev server
        run: yarn dev

  cypress-run:
    needs: local-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm start
